dhcpv6: add setting to choose IA_NA, IA_PD or both
openwrt/odhcpd pull request #118
Opened 2018-12-21 15:18 UTC by mamidzic

This commit implements feature request #111 
Adds the config option to set if DHCPv6 'stateful addresing' hands out
IA_NA (Internet Address - Network Address), IA_PD (Internet Address -
Prefix Delegation), both or none.

The config option is the 'dhcpv6_stateful_type' of type integer, possible options are :
0		No IA_* types available
1		IA_NA only available
2		IA_PD only available
3		IA_PD and IA_NA available
other integers are not checked, but in case other integers are used in this option it will be treated like a '0'.

If 'ra_managed' option is '0', the 'dhcpv6_stateful_type' IA_NA and IA_PD are handed out.
The default setting for 'dhcpv6_stateful_type'  is '3', so if 'ra_managed' is '1' and the 'dhcpv6_stateful_type' option isn't set in the config, IA_NA and IA_PD are handed out.

Codes for NoAddrsAvail or NoPrefixAvail are returned if IA_NA or IA_PD are set not to be handed out.

Signed-off-by: Matija Amidzic <matija.amidzic@sartura.hr>

2018-12-21 17:11 UTC, dedeckeh requested changes

2018-12-21 17:11 UTC, dedeckeh commented on src/config.c
> +	IFACE_ATTR_STATEFUL_TYPE,
I prefer to split this out in separate config options

- IFACE_ATTR_DHCPV6_PD => config option dhcpv6_pd
- IFACE_ATTR_DHCPV6_NA => config option dhcpv6_na

2018-12-21 17:11 UTC, dedeckeh commented on src/odhcpd.h
> +	int dhcpv6_stateful_type;
Split this out in dhcpv6_na and dhcpv6_pd which are enabled by default

2018-12-21 17:11 UTC, dedeckeh commented on src/config.c
> +	if (iface->ra_managed == 0) {
Don't make the link to ra_managed as I don't want to link this

2019-01-07 15:25 UTC, mamidzic commented
Hi, I've made the requested changes.

2019-01-08 15:14 UTC, dedeckeh commented
Can you also update the README with the newly added uci parameters ?

2019-01-14 09:31 UTC, mamidzic commented
I've updated the README file also.

2019-01-14 20:26 UTC, dedeckeh requested changes

2019-01-14 20:26 UTC, dedeckeh commented on src/config.c
> +	IFACE_ATTR_DHCPV6_PD,
Move both lines after IFACE_ATTR_DHCPV6_ASSIGNALL (line 47)

2019-01-14 20:26 UTC, dedeckeh commented on src/config.c
> +	[IFACE_ATTR_DHCPV6_PD] = { .name = "dhcpv6_pd", .type = BLOBMSG_TYPE_BOOL },
Move both lines after IFACE_ATTR_DHCPV6_ASSIGNALL (line 93)

2019-01-14 20:26 UTC, dedeckeh commented on src/config.c
> +		iface->dhcpv6_pd = blobmsg_get_u32(c);
A boolean is read by using blobmsg_get_bool(c). Move this also after parsing tb[IFACE_ATTR_DHCPV6_ASSIGNALL]

2019-01-14 20:26 UTC, dedeckeh commented on src/config.c
> +		iface->dhcpv6_na = blobmsg_get_u32(c);
A boolean is read by using blobmsg_get_bool(c). Move this also after parsing tb[IFACE_ATTR_DHCPV6_ASSIGNALL]

2019-01-15 08:09 UTC, mamidzic commented
The changes you requested are done.

2019-01-15 12:32 UTC, dedeckeh commented
Patch pushed to master (https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=7abbed4fba6c9b75ec5331291eb7dc787f99a977); thx

2019-01-15 12:32 UTC, closed without merging