dhcpv6-ia: allow up to 64 bit wide hostid
openwrt/odhcpd pull request #173
Opened 2021-07-14 22:32 UTC by mikma

This PR implements up to 64 bit wide hostid for dynamic and static leases.

2021-08-02 19:29 UTC, dedeckeh requested changes

2021-08-02 19:29 UTC, dedeckeh commented on src/config.c
> +		if (hostid_len >= 12 && hostid_len <= 64)
Use a define for the minimum hostid length 12 and the maximum hostid length 64

2021-08-02 19:29 UTC, dedeckeh commented on src/odhcpd.h
> +	uint64_t assigned;
Changing assigned into an uint64_t makes the code hard to understand and read in case of the prefix delegation logic as assigned is used to assign the subnet id

2021-08-02 19:29 UTC, dedeckeh commented on src/dhcpv6-ia.c
> +			do {
Align with the existing coding style by inserting an empty line before the do statement

2021-08-03 20:57 UTC, mikma commented on src/config.c
> +		if (hostid_len >= 12 && hostid_len <= 64)
Fixed.

2021-08-03 20:57 UTC, mikma commented on src/dhcpv6-ia.c
> +			do {
Fixed.

2021-08-03 20:59 UTC, mikma commented on src/odhcpd.h
> +	uint64_t assigned;
I have changed `assigned` into an anonymous union with members `uint64_t assigned_host_id` and `uint32_t assigned_subnet_id`.

2021-08-04 19:35 UTC, dedeckeh commented
Can you squash all the commits into one commit as they're all related to the same feature

2021-08-04 21:33 UTC, mikma commented
I have squashed and rebased on master at git.openwrt.org.

I also added a check against the reserved IPv6 interface identifier ranges listed at http://www.iana.org/assignments/ipv6-interface-ids .

2021-08-07 16:30 UTC, dedeckeh commented
This fails to compile for me with the following error

src/dhcpv6-ia.c: In function 'dhcpv6_ia_write_statefile':
src/dhcpv6-ia.c:367:54: error: format '%zx' expects argument of type 'size_t', but argument 10 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
      ctxt.buf_idx = snprintf(ctxt.buf, ctxt.buf_len, "# %s %s %x %s%s %"PRId64" %zx %u ",
                                                      ^~~~~~~~~~~~~~~~~~~
src/dhcpv6-ia.c:374:9:
         (ctxt.c->flags & OAF_DHCPV6_NA) ? ctxt.c->assigned_host_id : ctxt.c->assigned_subnet_id,
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/dhcpv6-ia.c:367:83: note: format string is defined here
      ctxt.buf_idx = snprintf(ctxt.buf, ctxt.buf_len, "# %s %s %x %s%s %"PRId64" %zx %u ",
                                                                                 ~~^
                                                                                 %llx

As assigned_hostìd is an uint64_t the best option is to move this to two separate snprintf lines depending on the assignment type

2021-08-10 20:30 UTC, mikma commented
I have duplicated the snprintf statements and I use the PRIx64/32-macros in the format string now.

2021-08-14 19:47 UTC, dedeckeh commented
Patch pushed to master with a minor modification (https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=16667699228101fda936068e3d11c0cf19270e34); thx

2021-08-14 19:47 UTC, closed without merging