fix: DHCPv6 does not respect prefix assigned to interface (<=/64)
openwrt/odhcpd pull request #219
Opened 2024-04-29 07:30 UTC by xvzf

fixes #199

Signed-off-by: Matthias Riegler <matthias.riegler@ankorstore.com>

2025-10-01 21:57 UTC, systemcrash commented
ping @dedeckeh @Noltari 

This fixes an edge case (see "Fixes" discussion).

2025-10-02 09:19 UTC, Noltari requested changes

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +
I think we should move these to functions to the top and make them inline.
That way we don't need to add declarations at the top.

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +static uint32_t mask_low_for_hostid(uint8_t dhcpv6_hostid_len) {
Please, move the `{` to the next line:
```
static uint32_t mask_low_for_hostid(uint8_t dhcpv6_hostid_len)
{
```

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len) {
Please, move the `{` to the next line:
```
static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len)
{
```

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +			uint32_t mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
Can we move the `uint32_t` declarations to the start of the block?
```
if (c->flags & OAF_DHCPV6_NA) {
	uint32_t mask_high, mask_low;

	if (!ADDR_ENTRY_VALID_IA_ADDR(iface, i, m, addrs))
		continue;

	mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
	mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);

	...
}
```

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +      try <<= (64 - iface->addr6_len);
Please indent this properly with tabs.

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +    return (1 << (dhcpv6_hostid_len - 32)) - 1;
Please indent this properly with tabs.

2025-10-02 09:19 UTC, Noltari commented on src/dhcpv6-ia.c
> +				));
Remove the double `(( .. ))` from `htnol`.

2025-10-07 13:55 UTC, systemcrash commented
Still needs fixes @xvzf

2025-10-22 13:18 UTC, systemcrash commented on src/dhcpv6-ia.c
> +      try <<= (64 - iface->addr6_len);
@xvzf

2025-10-22 13:18 UTC, systemcrash commented on src/dhcpv6-ia.c
> +    // If prefix is < 64 bits, we need to shift the IID to the left
InterfaceID

2025-10-22 13:19 UTC, systemcrash commented on src/dhcpv6-ia.c
> +				));
@xvzf

2025-10-22 13:19 UTC, systemcrash commented on src/dhcpv6-ia.c
> +				));
here also @xvzf

2025-10-22 13:41 UTC, Noltari commented
I think I've fixed all the comments myself, so please @systemcrash confirm when you can and I'll merge this.

2025-10-22 13:49 UTC, systemcrash commented on src/dhcpv6-ia.c
> +				& (~mask_low & ntohl(addrs[i].addr.in6.s6_addr32[3]))
these?

2025-10-22 13:54 UTC, systemcrash commented on src/dhcpv6-ia.c
> +				& (~mask_low & ntohl(addrs[i].addr.in6.s6_addr32[3]))
Ah sorry. Blind. All good :)

2025-10-22 13:54 UTC, Noltari commented on src/dhcpv6-ia.c
> +				& (~mask_low & ntohl(addrs[i].addr.in6.s6_addr32[3]))
Do you mean the double parentheses that I reported?
If that's the case they are needed but they were poorly placed in different lines and I've moved them where they belong.

2025-10-22 13:54 UTC, systemcrash commented
LGTM

2025-10-22 14:04 UTC, systemcrash commented
Actually, can you reword the commit message so it says >= 64?

2025-10-22 14:06 UTC, systemcrash commented
I know - it's sometimes confusing. But in math 96 > 64. A 96 bit prefix is in fact greater than a 64 bit prefix, though the result is that the subnet space is 'smaller' as a result.

2025-10-22 14:07 UTC, merged

2025-10-22 14:08 UTC, Noltari commented
Merged, thanks @xvzf!

2025-10-23 14:02 UTC, xvzf commented
Thx @Noltari and sorry for not getting back earlier to this; has been dangling around quite long